"""Add api_keys table with users and brokers relationships

Revision ID: 1d7d74076e55
Revises: 1742610489e5
Create Date: 2025-08-16 20:37:46.359156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d7d74076e55'
down_revision: Union[str, Sequence[str], None] = '1742610489e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('api_key', sa.String(), nullable=False),
    sa.Column('private_key', sa.String(), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.Column('brokers_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['brokers_name'], ['brokers.name'], ),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('users_id', 'brokers_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_keys')
    # ### end Alembic commands ###
