"""Initial revision

Revision ID: 1eae5be6baa2
Revises: 
Create Date: 2025-09-12 15:58:37.244794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1eae5be6baa2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brokers',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', postgresql.ARRAY(sa.Enum('stocks', 'crypto', name='asset_type')), nullable=False),
    sa.Column('private_key_required', sa.Boolean(), nullable=False),
    sa.Column('rate_limit', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('api_keys',
    sa.Column('api_key', sa.String(), nullable=False),
    sa.Column('private_key', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('broker_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['broker_name'], ['brokers.name'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'broker_name')
    )
    op.create_table('portfolios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portfolio', sa.JSON(), nullable=False),
    sa.Column('last_updated', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('broker_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['broker_name'], ['brokers.name'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('broker_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('portfolios')
    op.drop_table('api_keys')
    op.drop_table('users')
    op.drop_table('brokers')
    # ### end Alembic commands ###
