"""Add enum attribute 'type' to brokers table

Revision ID: 2b3d03bd3a03
Revises: 1d7d74076e55
Create Date: 2025-08-18 18:22:29.509225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2b3d03bd3a03'
down_revision: Union[str, Sequence[str], None] = '1d7d74076e55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    type_enum = postgresql.ENUM('stocks', 'crypto', name='type_enum')
    type_enum.create(op.get_bind())
    op.add_column('brokers', sa.Column('type', postgresql.ARRAY(type_enum), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brokers', 'type')
    type_enum = postgresql.ENUM('stocks', 'crypto', name='type_enum')
    type_enum.drop(op.get_bind())
    # ### end Alembic commands ###
