"""Add id and last_updated attributes to portfolios, add brokers relationship

Revision ID: 430bee9949d6
Revises: 63d9f3a19742
Create Date: 2025-08-26 22:57:00.247524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '430bee9949d6'
down_revision: Union[str, Sequence[str], None] = '63d9f3a19742'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolios', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('portfolios', sa.Column('last_updated', sa.DateTime(), nullable=False))
    op.add_column('portfolios', sa.Column('brokers_name', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'portfolios', ['brokers_name'])
    op.create_foreign_key(None, 'portfolios', 'brokers', ['brokers_name'], ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'portfolios', type_='foreignkey')
    op.drop_constraint(None, 'portfolios', type_='unique')
    op.drop_column('portfolios', 'brokers_name')
    op.drop_column('portfolios', 'last_updated')
    op.drop_column('portfolios', 'id')
    # ### end Alembic commands ###
