"""Fix autoincrement for id in portfolios table

Revision ID: 44fec2d234ed
Revises: 72ca39e0b4f9
Create Date: 2025-09-08 19:06:54.593309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44fec2d234ed'
down_revision: Union[str, Sequence[str], None] = '72ca39e0b4f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'portfolios', ['broker_name'])
    op.execute("CREATE SEQUENCE IF NOT EXISTS portfolios_id_seq START 1")
    op.execute("""
               ALTER TABLE portfolios
                   ALTER COLUMN id SET DEFAULT nextval('portfolios_id_seq');
               """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'portfolios', type_='unique')
    # ### end Alembic commands ###
