"""Add order_history attribute of JSON type to portfolios table

Revision ID: 50fe7557a53d
Revises: 1eae5be6baa2
Create Date: 2025-09-29 21:26:50.348280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50fe7557a53d'
down_revision: Union[str, Sequence[str], None] = '1eae5be6baa2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolios', sa.Column('order_history', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolios', 'order_history')
    # ### end Alembic commands ###
