"""Add rate_limit attribute to brokers table

Revision ID: 5b645a39ff2c
Revises: 44fec2d234ed
Create Date: 2025-09-12 15:14:30.489912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b645a39ff2c'
down_revision: Union[str, Sequence[str], None] = '44fec2d234ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brokers', sa.Column('rate_limit', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brokers', 'rate_limit')
    # ### end Alembic commands ###
