"""Remove attribute order_history from portfolio table

Revision ID: 620d2ce9c49c
Revises: 50fe7557a53d
Create Date: 2025-09-29 21:30:14.370675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '620d2ce9c49c'
down_revision: Union[str, Sequence[str], None] = '50fe7557a53d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolios', 'order_history')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolios', sa.Column('order_history', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
