"""Make all table attributes singular

Revision ID: 72ca39e0b4f9
Revises: 430bee9949d6
Create Date: 2025-09-08 17:16:26.922604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72ca39e0b4f9'
down_revision: Union[str, Sequence[str], None] = '430bee9949d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('api_keys', sa.Column('broker_name', sa.String(), nullable=False))
    op.drop_constraint(op.f('api_keys_brokers_name_fkey'), 'api_keys', type_='foreignkey')
    op.drop_constraint(op.f('api_keys_users_id_fkey'), 'api_keys', type_='foreignkey')
    op.create_foreign_key(None, 'api_keys', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'api_keys', 'brokers', ['broker_name'], ['name'])
    op.drop_column('api_keys', 'users_id')
    op.drop_column('api_keys', 'brokers_name')
    op.add_column('portfolios', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('portfolios', sa.Column('broker_name', sa.String(), nullable=True))
    op.drop_constraint(op.f('portfolios_brokers_name_key'), 'portfolios', type_='unique')
    op.create_unique_constraint(None, 'portfolios', ['broker_name'])
    op.drop_constraint(op.f('portfolios_brokers_name_fkey'), 'portfolios', type_='foreignkey')
    op.drop_constraint(op.f('portfolios_users_id_fkey'), 'portfolios', type_='foreignkey')
    op.create_foreign_key(None, 'portfolios', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'portfolios', 'brokers', ['broker_name'], ['name'])
    op.drop_column('portfolios', 'users_id')
    op.drop_column('portfolios', 'brokers_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolios', sa.Column('brokers_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('portfolios', sa.Column('users_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'portfolios', type_='foreignkey')
    op.drop_constraint(None, 'portfolios', type_='foreignkey')
    op.create_foreign_key(op.f('portfolios_users_id_fkey'), 'portfolios', 'users', ['users_id'], ['id'])
    op.create_foreign_key(op.f('portfolios_brokers_name_fkey'), 'portfolios', 'brokers', ['brokers_name'], ['name'])
    op.drop_constraint(None, 'portfolios', type_='unique')
    op.create_unique_constraint(op.f('portfolios_brokers_name_key'), 'portfolios', ['brokers_name'], postgresql_nulls_not_distinct=False)
    op.drop_column('portfolios', 'broker_name')
    op.drop_column('portfolios', 'user_id')
    op.add_column('api_keys', sa.Column('brokers_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('api_keys', sa.Column('users_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'api_keys', type_='foreignkey')
    op.drop_constraint(None, 'api_keys', type_='foreignkey')
    op.create_foreign_key(op.f('api_keys_users_id_fkey'), 'api_keys', 'users', ['users_id'], ['id'])
    op.create_foreign_key(op.f('api_keys_brokers_name_fkey'), 'api_keys', 'brokers', ['brokers_name'], ['name'])
    op.drop_column('api_keys', 'broker_name')
    op.drop_column('api_keys', 'user_id')
    # ### end Alembic commands ###
