"""Add columns for user.id and broker.name and set them as FK

Revision ID: 79891ed2f5bc
Revises: 0b0a3539dfbd
Create Date: 2025-06-29 21:12:56.579521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79891ed2f5bc'
down_revision: Union[str, Sequence[str], None] = '0b0a3539dfbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brokers',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('name'),
    sa.UniqueConstraint('name')
    )
    op.drop_table('broker')
    op.add_column('api_keys', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('api_keys', sa.Column('broker_name', sa.String(length=128), nullable=False))
    op.create_foreign_key(None, 'api_keys', 'brokers', ['broker_name'], ['name'])
    op.create_foreign_key(None, 'api_keys', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'api_keys', type_='foreignkey')
    op.drop_constraint(None, 'api_keys', type_='foreignkey')
    op.drop_column('api_keys', 'broker_name')
    op.drop_column('api_keys', 'user_id')
    op.create_table('broker',
    sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.UniqueConstraint('name', name=op.f('broker_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('brokers')
    # ### end Alembic commands ###
