"""Add brokers and api_keys tables with relationships

Revision ID: 87fd06e2b709
Revises: a07ca277dd2a
Create Date: 2025-11-04 18:35:48.988874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87fd06e2b709'
down_revision: Union[str, Sequence[str], None] = 'a07ca277dd2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('api_key', sa.String(), nullable=False),
    sa.Column('secret_key', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('broker_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['broker_name'], ['brokers.name'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'broker_name')
    )
    op.create_unique_constraint(None, 'brokers', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'brokers', type_='unique')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
