"""Add private_key_required field to brokers

Revision ID: a08b710c11e4
Revises: d33c293b3183
Create Date: 2025-08-20 21:06:17.730710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a08b710c11e4'
down_revision: Union[str, Sequence[str], None] = 'd33c293b3183'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brokers', sa.Column('private_key_required', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brokers', 'private_key_required')
    # ### end Alembic commands ###
