"""Let private_key be nullable in ApiKey table

Revision ID: b9262502df4c
Revises: a08b710c11e4
Create Date: 2025-08-21 21:21:08.651977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9262502df4c'
down_revision: Union[str, Sequence[str], None] = 'a08b710c11e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('api_keys', 'private_key',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('api_keys', 'private_key',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
