"""Add portfolio cash table with attributes and candidate keys

Revision ID: e012cbc2ae70
Revises: 87fd06e2b709
Create Date: 2025-11-13 23:53:22.612399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e012cbc2ae70'
down_revision: Union[str, Sequence[str], None] = '87fd06e2b709'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolios_cash',
    sa.Column('free', sa.Float(), nullable=False),
    sa.Column('invested', sa.Float(), nullable=False),
    sa.Column('profit_and_loss', sa.Float(), nullable=False),
    sa.Column('result', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('broker_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['broker_name'], ['brokers.name'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'broker_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('portfolios_cash')
    # ### end Alembic commands ###
